var TEMPLATES = [
	{name: "经典模板", path: "classic/classic"},
	{name: "经典模板（卤粉）", path: "classic/lufen"},
	{name: "经典卡牌模板", path: "classic/cards"},
	{name: "Q版模板", path: "chibi"},
	{name: "国战模板", path: "guozhan"},
	{name: "三国杀2020模板", path: "diy2020"},
	{name: "官方模板（自定配色）", path: "classic/custom-colored"},
	{name: "桌游志·☆SP模板", path: "star-sp"},
	{name: "桌游志·全幅模板", path: "spcloud"},
	{name: "欢乐三国杀模板", path: "xhlsgs"},
	{name: "移动版模板", path: "mobile"},
	{name: "动漫模板", path: "anime"},
	{name: "印花模板", path: "yinhua"},
	{name: "YL超大幅模板", path: "ylhuge"},
	{name: "帝国3模板", path: "aoe3"},
	{name: "洛吧杀模板", path: "rockman"},
	{name: "狼羊志模板", path: "langyangzhi"}
];